name: Greetings

on:
  [pull_request_target, issues] 

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write  
      pull-requests: write  
    steps:
      - name: Greet first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome! Thank you for opening your first issue. The maintainers will review it soon. 🚀"
          pr-message: "🎉 Congratulations on submitting your first PR! The team will review it shortly. Keep contributing! 💪"
